//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


#define SomeUtility_SomeService_CTOR ActionReq1.SetServiceFunc([](SomeUtility* p, uint32_t num1, uint32_t num2){p->_SomeService( num1,  num2); });


//SomeService----------------------------------------------

	  
	  
	#define SomeUtility_SomeService_Service \
	inline void SomeService(int idOfAO, uint32_t num1, uint32_t num2)\
	{\
		this->RunRequest1(idOfAO,  num1,  num2); \
	}\
	\
	inline Token* SomeService_WithWait(int idOfAO, uint32_t num1, uint32_t num2)\
	{\
		return this->RunRequestWithWait1(idOfAO,  num1,  num2); \
	}\
	\
	inline Action1_RETURNTYPE_t SomeService_WaitForRequestToFinish(Token* token)\
	{\
		return this->WaitForRequestToFinish1(token  ); \
	}\
	\
	inline void SomeService_DoneWithRequest(Token* tokenOfRequest)\
	{\
		return this->DoneWithRequest1(tokenOfRequest); \
	}\
	inline Action1_RETURNTYPE_t SomeService_WaitHereForFinish(int idOfAO, uint32_t num1, uint32_t num2)\
	{\
		auto token = this->RunRequestWithWait1(idOfAO,  num1,  num2);\
		Action1_RETURNTYPE_t ret = this->WaitForRequestToFinish1(token);\
		this->DoneWithRequest1(token);\
		return ret;\
	}
	
	#define SomeUtility_SomeService void _SomeService(int idOfAO, uint32_t num1, uint32_t num2)
	#define SomeUtility_SomeService_Update bool _SomeServiceUpdate(ActionRequestObjectArgTDU-2* actReq, uint32_t num1, uint32_t num2)   
//Alldefines ------------------
#define SomeUtility_CTOR \
SomeUtility_SomeService_CTOR 
#define SomeUtility_Service \
SomeUtility_SomeService_Service 
