//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################



using CgenMin.MacroProcesses;
using CodeGenerator.MacroProcesses.AESetups;
using CodeGenerator.MacroProcesses.AESetups.SPBs;
using System.Collections.Generic;

namespace AEHalTestsProject
{

    public class AEHalTests : AEProject
    {
		[AEEXETest]
        public void ADC_TEST()
        {

        }

        [AEEXETest]
        public void UART_TEST()
        {

        }

        [AEEXETest]
        public void PWM_TEST()
        {

        }


        [AEEXETest]
        public void I2C_TEST()
        {

        }


        [AEEXETest]
        public void SPI_TEST()
        {

        }




        

        protected override string _GetDirectoryOfLibrary()
        {
            return @"C:\AERTOS\AERTOS\src\AE\hal\AEHalTests"; 
        }

        protected override List<AEEvent> _GetEventsInLibrary()
        {
            return new List<AEEvent>() { I2C_RXCpltEVT.Init(5) };
        }

		protected override List<AEHal> _GetPeripheralsInLibrary()
        {
            //ADCPERIPHERAL1_CH1.Init(Portenum.PortB, PinEnum.PIN0)
            return new List<AEHal>() {
                ADCPERIPHERAL1_CH1.Init(Portenum.PortB, PinEnum.PIN0),
                ADCPERIPHERAL1_CH2.Init(Portenum.PortA, PinEnum.PIN2),
                ADCPERIPHERAL1_CH3.Init(Portenum.PortA, PinEnum.PIN3),
                UARTPERIPHERAL2.Init(BaudRatesEnum.T_115200,1,Portenum.PortD, PinEnum.PIN5, Portenum.PortD, PinEnum.PIN6),
                PWMPERIPHERAL1.Init(Portenum.PortD, PinEnum.PIN13),
                I2CPERIPHERAL1.Init(10000, Portenum.PortB, PinEnum.PIN6, Portenum.PortB, PinEnum.PIN7),
                SPIPERIPHERAL1.Init(false,Portenum.PortA, PinEnum.PIN5, Portenum.PortA, PinEnum.PIN6, Portenum.PortA, PinEnum.PIN7, Portenum.PortA, PinEnum.PIN4)
            };
        }


        protected override List<AEProject> _GetLibrariesIDependOn()
        {
            return new List<AEProject>() {  };
        }
		
		protected override List<string> _GetAnyAdditionalIncludeDirs()
        {
            return new List<string>() { };
        }

        protected override List<string> _GetAnyAdditionalSRCDirs()
        {
            return new List<string>() { };
        }

    }
	
	
	
}