//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

//Macro2 - AERTOS\AEProjectCS.cgenMM::TopLevel


using CgenMin.MacroProcesses;
using System.Collections.Generic;

namespace AESamplesProject
{

    public class AESamples : AEProject
    {

        [AEEXETest]
        public void SPBSamples()
        {

        }

        protected override string _GetDirectoryOfLibrary()
        {
            return @"C:/AERTOS/AERTOS/src/AE/AESamples";
        }

        protected override List<AEEvent> _GetEventsInLibrary()
        {
            return new List<AEEvent>() { };
        }


        protected override List<AEProject> _GetLibrariesIDependOn()
        {
            return new List<AEProject>() { };
        }

        protected override List<AEHal> _GetPeripheralsInLibrary()
        {
            return null;
        }

        //protected override List<string> _GetListOfTests()
        //{
        //    return new List<string>() { "SPBSamples" };
        //}
    }

}