//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

//Macro2 - AERTOS\AEProjectCS.cgenMM::TopLevel


using CgenMin.MacroProcesses;
using CGENTestProject;
using CodeGenerator.MacroProcesses.AESetups.SPBs;
using System.Collections.Generic;

namespace CGENTest2Project
{

    public class CGENTest2 : AEProject
    {

        [AEEXETest]
        public void default2()
        {

        }

        protected override string _GetDirectoryOfLibrary()
        {
            return @"C:/CodeGenerator/CodeGenerator/macro2Test/CGENTest2";
        }

        protected override List<AEEvent> _GetEventsInLibrary()
        {
            return new List<AEEvent>() { I2C_RXCpltEVT.Init(10) };
        }


        protected override List<AEProject> _GetLibrariesIDependOn()
        { 
            return new List<AEProject>() {(AEProject) new CGENTest()};
        }
        protected override List<AEHal> _GetPeripheralsInLibrary()
        {
            return null;
        }

        

    }
}