//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################



using CgenMin.MacroProcesses;
using CGENTest2Project;
using CGENTestProject;
using CodeGenerator.MacroProcesses.AESetups;
using CodeGenerator.MacroProcesses.AESetups.SPBs;
using System.Collections.Generic;

namespace CGENTest3Project
{



    class SomeUtility : AEUtilityService
    {
        public SomeUtility(string instanceNameOfTDU, int serviceBuffersize, AEPriorities priority)
            : base("CGENTest3", instanceNameOfTDU, priority, serviceBuffersize,
                  new CppFunctionArgs(
                        
                        ),
                  new ActionRequest("SomeService", ServiceType.Normal, "uint32_t", "uint32_t", "num1", "uint32_t", "num2")
                  )
        {
        }
    }



    public class CGENTest3 : AEProject
    {
		[AEEXETest]
        public void defaultTest()
        {
            BlindsUITOPFSM blinduifsm = new BlindsUITOPFSM("blinduifsm", AEPriorities.MediumPriority);
            ConfiguringFSM configfsm = new ConfiguringFSM("configfsm", AEPriorities.MediumPriority);
            NormalOperationFSM normalfsm = new NormalOperationFSM("normalfsm ", AEPriorities.MediumPriority);

            AELoopObjectTest2 aELoopObjectTest2 = new AELoopObjectTest2("loopobjectTest2", AEPriorities.MediumPriority, 3);

            SomeUtility someUtility = new SomeUtility("someUtility",10, AEPriorities.MediumPriority);
        }

        protected override string _GetDirectoryOfLibrary()
        {
            return @"C:\CodeGenerator\CodeGenerator\macro2Test\CGENTest3"; 
        }

        protected override List<AEEvent> _GetEventsInLibrary()
        {
            return new List<AEEvent>() { I2C_RXCpltEVT.Init(10),
                          Button1.Init(10),
                Button2.Init(10),
                Button3.Init(10)};
        }

		protected override List<AEHal> _GetPeripheralsInLibrary()
        {
		//ADCPERIPHERAL1_CH1.Init(Portenum.PortB, PinEnum.PIN0)
            return new List<AEHal>() { 
            };
        }

        protected override List<AEProject> _GetLibrariesIDependOn()
        {
            return new List<AEProject>() {new CGENTest2() };
        }

        protected override List<string> _GetAnyAdditionalIncludeDirs()
        {
            return new List<string>() { };
        }
        protected override List<string> _GetAnyAdditionalSRCDirs()
        {
            return new List<string>() { };
        }

    }
	
	
	
}