//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

//Macro2 - AERTOS/EventsForProject.cgenMM::TopLevel
 #pragma once
  
#include "AEEventBase.h"
  
  
  
//Macro2 - AERTOS/AEEvent.cgenMM::TopLevel
 
  
class I2C_RXCpltEVT : public AEEventBase
{
public: 
	static EventPoolSize_t EvtIdStatic;

	uint8_t forI2C;
 
	 
};
 