//****************************************************
//This is an autogenerated configuration file
//****************************************************
//---------DO NOT EDIT THIS FILE ----------------




//****************************************************
//autogenerated enum types 
//****************************************************

#define PLATFORM_QP  0
#define PLATFORM_IAR  1
#define PLATFORM_VS  2
#define BUILD_DEBUG  0
#define BUILD_RELEASE  1
#define BUILD_TESTING  2
#define MODE_Fast  0
#define MODE_Slow  1


//****************************************************
//defines for the local program. 
//names of defines will be prefixName+suffixMajor_prefixInstance_defineName_instanceOfconfig
//****************************************************

#define PLATFORM  1
#define BUILD  0
#define BUFFERSIZE  59
#define MSG1  "kihi"
#define MSG2  "hello again!!!"
#define BUFFERSIZELOCAL  50
#define MAJOR  1
#define MODE  0
