//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

//Macro2 - AERTOS\IntegTestPipeline.cgenMM::TopLevel
#pragma once

void RunSelectedIntegrationTest_CGENTest();

static void RunSelectedIntegrationTest()
{
    RunSelectedIntegrationTest_CGENTest();
}
