//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

//Macro2 - AERTOS\main.cgenMM::TopLevel

/* Includes ------------------------------------------------------------------*/


//#include <../CMSIS_RTOS/cmsis_os.h>

#include "IntegTestPipeline.h"

int main(void)
{

	RunSelectedIntegrationTest();
}

 