//****************************************************
//This is an autogenerated configuration file
//****************************************************
//---------DO NOT EDIT THIS FILE ----------------




//****************************************************
//autogenerated enum types 
//****************************************************

#define PLATFORM_QP  0
#define PLATFORM_IAR  1
#define PLATFORM_VS  2
#define BUILD_DEBUG  0
#define BUILD_RELEASE  1
#define BUILD_TESTING  2
#define Speed_Fast  0
#define Speed_Slow  1


//****************************************************
//defines for the local program. 
//names of defines will be prefixName+suffixMajor_prefixInstance_defineName_instanceOfconfig
//****************************************************

#define PLATFORM  2
#define BUILD  0
#define BUFFERSIZE  84
#define Speed  0
#define MAJOR  0
