//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

//Macro2 - inputs\inputtest1.cgenMM::TopLevel
class something
{
	something()
	{}
	
	int hello;
	
	
//Macro2 - inputs\SetPosxInput.cgenMM::Section2
//Macro2: Section2
void Setposx(int p)
{
//Macro2: SomeDynamicStuff
	int somestuff = 4;
	data->posx = p;
}

int Getposx()
{
//Macro2: SomeDynamicStuff
	int somestuff = 4;
	return data->posx;
}

//Macro2 - inputs\SetPosxInput.cgenMM::Section2
void Setposy(float p)
{
//Macro2: SomeDynamicStuff
	int somestuff = 4;
	data->posy = p;
}

float Getposy()
{
//Macro2: SomeDynamicStuff
	int somestuff = 4;
	return data->posy;
}


	
	
	
	string blabla;
	int fdgr;

};
