//****************************************************
//This is an autogenerated configuration file
//****************************************************
//---------DO NOT EDIT THIS FILE ----------------




//****************************************************
//autogenerated enum types 
//****************************************************

#define PLATFORM_QP  0
#define PLATFORM_IAR  1
#define PLATFORM_VS  2
#define BUILD_DEBUG  0
#define BUILD_RELEASE  1
#define BUILD_TESTING  2


//****************************************************
//defines for the local program. 
//names of defines will be prefixName+suffixMajor_prefixInstance_defineName_instanceOfconfig
//****************************************************

#define PLATFORM  2
#define BUILD  0
#define BUFFERSIZE  42
#define BUFFERSIZE2  24
#define MAJOR  0
