//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

#pragma once 

#define AEITEST_END_TestsAfterTimer_CGENTest(timeInMilliBeforeEnd) 
#define AEITEST_CGENTest(testName, thingToAssert, AssertionMessage) 
#define AEITEST_CGENTest_MUST_PASS_THIS_MANY(testName, thingToAssert, AssertionMessage, passedOnlyAfterThisManyPasses) 
#define AEITEST_CGENTest_IgnoreFirstTests(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum) 
#define AEITEST_EndTestsIfFalseAssertion_CGENTest(testName, thingToAssert, AssertionMessage) 
#define AEITEST_END_CGENTest 
#define AEITEST_EXPECT_TEST_TO_RUN_CGENTest(testName) 
 

#if BUILD_TESTS__TRUE
//** <h4>integration test enders: will end the test in various ways</h4>*// 
//** the following will end the test after a certain time in milli has passed*// 
#define AEITEST_END_TestsAfterTimer_CGENTest2(timeInMilliBeforeEnd) _AEITEST_END_TestsAfterTimer(timeInMilliBeforeEnd)
#define AEITEST_CGENTest2(testName, thingToAssert, AssertionMessage) _AEITEST(testName, thingToAssert, AssertionMessage,0,1) 
#define AEITEST_CGENTest2_MUST_PASS_THIS_MANY(testName, thingToAssert, AssertionMessage, passedOnlyAfterThisManyPasses) _AEITEST(testName, thingToAssert, AssertionMessage, 0,passedOnlyAfterThisManyPasses) 
#define AEITEST_CGENTest2_IgnoreFirstTests(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum) _AEITEST(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum,1) 
#define AEITEST_EndTestsIfFalseAssertion_CGENTest2(testName, thingToAssert, AssertionMessage) _AEITEST_EndTestsIfFalseAssertion(testName, thingToAssert, AssertionMessage) 
#define AEITEST_END_CGENTest2 _AEITEST_END
#define AEITEST_EXPECT_TEST_TO_RUN_CGENTest2(testName) _AEITEST_EXPECT_TEST_TO_RUN(testName)
 
#else
#define AEITEST_END_TestsAfterTimer_CGENTest2(timeInMilliBeforeEnd) 
#define AEITEST_CGENTest2(testName, thingToAssert, AssertionMessage) 
#define AEITEST_CGENTest2_MUST_PASS_THIS_MANY(testName, thingToAssert, AssertionMessage, passedOnlyAfterThisManyPasses) 
#define AEITEST_CGENTest2_IgnoreFirstTests(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum) 
#define AEITEST_EndTestsIfFalseAssertion_CGENTest2(testName, thingToAssert, AssertionMessage) 
#define AEITEST_END_CGENTest2 
#define AEITEST_EXPECT_TEST_TO_RUN_CGENTest2(testName) 
 
#endif